### ISSUE TITLE
Use this action behind a proxy server

### ISSUE THREAD

**Issue by cristianomariano** [oracle-actions/get-ocir-repository#16]
Hi guys! How are you doing?
Is it possible to use this action behind a proxy server? We have tried to set HTTP_PROXY and HTTPS_PROXY environment variables, but it did not work.
Taking a look at the code, it looks like the SDK uses the isomorphic-fetch package, that does not consider the environment variables by default. Is this understanding correct?
Thank you very much!

**Comment by Djelibeybi** [comment]
Yes: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-a-proxy-server-with-self-hosted-runners

**Comment by cristianomariano** [comment]
Hi @Djelibeybi !
In fact, the action is being downloaded and executed, but it is trying to connect to OCI directly, even with the environment variables setup.
As soon as I am back to the PC, I will put the entire message here.
Thank you very much!

**Comment by Djelibeybi** [comment]
Could you also provvide more detail about your setup? You shouldn't need a proxy between GitHub and OCI and if you're self-hosting a runner, you should do that on OCI itself, so that it doesn't need a proxy either.

**Comment by Djelibeybi** [comment]
You should be able to use the `env` property of the job to set `https_proxy` which will be picked up by the OCI CLI automagically: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#cliconfigure_topic_Proxy_Server
